#!/bin/bash
# Helper script to configure Render deployment

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  KnowLedge Render Deployment Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Deploy your HF Space first:"
echo "   → Go to https://huggingface.co/spaces"
echo "   → Create new Space with SDK: Gradio, Hardware: CPU Basic"
echo "   → Upload files from hf_space/ folder"
echo ""
echo "2. Get your HF Space URL:"
echo "   → Format: https://your-username-your-space-name.hf.space"
echo ""
echo "3. Configure Render environment variables:"
echo "   → Go to https://dashboard.render.com"
echo "   → Select your knowledge service"
echo "   → Go to Environment tab"
echo "   → Add this variable:"
echo ""
echo "   Key:   HF_SPACE_URL"
echo "   Value: [paste your HF Space URL here]"
echo ""
echo "4. Redeploy:"
echo "   → Click 'Manual Deploy' → 'Deploy latest commit'"
echo ""
echo "5. Verify:"
echo "   → Visit https://your-app.onrender.com/api/status"
echo "   → Should show: \"ready\": true"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
